spring.application.name=SmartFleetPro

spring.datasource.url=jdbc:mysql://localhost:3306/smartfleet_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# ✅ Email OTP Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartfleetpro.project@gmail.com
spring.mail.password=fuzl vxaa ndzp wvri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true